# Generated by Django 6.1.1 on 2026-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
                ('recipient_type', models.CharField(choices=[('GUARDIAN', 'Primary Guardian'), ('SECURITY', 'Security Staff'), ('VOLUNTEER', 'Volunteer'), ('COMMUNITY', 'Community Member')], max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESPONDING', 'Responding'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
