# Generated by Django 6.1.1 on 2026-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertroute',
            name='status',
        ),
        migrations.AddField(
            model_name='alertroute',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='alertroute',
            name='response_status',
            field=models.CharField(choices=[('NO_RESPONSE', 'No Response'), ('RESPONDED', 'Responded'), ('RESPONDING', 'Responding'), ('RESOLVED', 'Resolved')], default='NO_RESPONSE', max_length=20),
        ),
        migrations.AddField(
            model_name='alertroute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
