# Generated by Django 6.1 on 2026-09-08 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencycontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_category', models.CharField(choices=[('medical', 'Medical'), ('security', 'Security'), ('fire', 'Fire'), ('accident', 'Accident'), ('other', 'Other')], default='medical', max_length=20)),
                ('response_timeout_seconds', models.IntegerField(default=60)),
                ('notify_guardians', models.BooleanField(default=True)),
                ('notify_security', models.BooleanField(default=True)),
                ('notify_volunteers', models.BooleanField(default=True)),
                ('community_broadcast', models.BooleanField(default=True)),
                ('location_sharing', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sos_configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
