# Generated by Django 6.1 on 2026-09-27 17:30

import django.db.models.deletion
import sos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0007_incidentmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDigitalTwinSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twin', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_digital_twin_snapshots', to='sos.sosincident')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_digital_twin_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeGraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_knowledge_graph_snapshots', to='sos.sosincident')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_knowledge_graph_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfflineIncidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message_id', models.CharField(default=sos.models.default_client_message_id, max_length=100, unique=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice')], default='TEXT', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='incident_offline_voice_messages/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('QUEUED', 'Queued'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('sync_attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_messages', to='sos.sosincident')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_incident_messages', to=settings.AUTH_USER_MODEL)),
                ('synced_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_source', to='sos.incidentmessage')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
