# Generated by Django 6.1 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0008_aidigitaltwinsnapshot_aiknowledgegraphsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosresponse',
            name='estimated_arrival_minutes',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Responder-provided estimated arrival time in minutes.',
                null=True,
            ),
        ),
    ]
