# Generated by Django 6.1 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0009_sosresponse_estimated_arrival_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosresponse',
            name='responder_role',
            field=models.CharField(
                blank=True,
                help_text='Role used for a local development dashboard preview, when applicable.',
                max_length=20,
                null=True,
            ),
        ),
    ]
