# Generated by Django 6.1 on 2026-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_name_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SUB_ADMIN', 'SUB_ADMIN'), ('SECURITY', 'SECURITY'), ('RESIDENT', 'RESIDENT'), ('VOLUNTEER', 'VOLUNTEER'), ('GUARDIAN', 'GUARDIAN')], default='GUARDIAN', max_length=20),
        ),
    ]
