# Generated by Django 6.1 on 2026-09-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SUB_ADMIN', 'SUB_ADMIN'), ('SECURITY', 'SECURITY'), ('RESIDENT', 'RESIDENT'), ('VOLUNTEER', 'VOLUNTEER'), ('GUARDIAN', 'GUARDIAN')], default='GUARDIAN', max_length=20),
        ),
    ]
