# Generated by Django 6.1 on 2026-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('incharge', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
