# Generated by Django 6.1 on 2026-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('society_name', models.CharField(max_length=100)),
            ],
        ),
    ]
